version: '3.9'
services:
  satellite-pollination-map:
    build: .
    command: python3 /app/server.py
    environment:
      ENV_ID: dev
    ports:
      - 9500:9500
    volumes:
      - .:/app/
    network_mode: bridge
    tty: true
    restart: always
    networks:
      - gratheon
networks:
  gratheon:
